In [1]:
import numpy as np
x=np.array(["A",67,57,9,8])
print(x)
print(type(x))
print(x.dtype)

['A' '67' '57' '9' '8']
<class 'numpy.ndarray'>
<U11


In [3]:
a2 = np.array([[20,40],[30,60]])
print(a2)
print(type(a2))
print(a2.shape)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
(2, 2)


In [4]:
a=np.array([10,20,30,40])
b=a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [5]:
d=np.array([1.23465,3.45674,4.7907])

In [8]:
a1=np.array([[78,9,3,4],[7,58,48,3,np.NAN]])
print(a1)
a1.dtype

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [10]:
a2=np.array([[3,4,5],[7,8,9],[2,3,7]])
a2

array([[3, 4, 5],
       [7, 8, 9],
       [2, 3, 7]])

In [12]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])


In [14]:
a4=np.array([[3,4,5],[7,8,9],[2,3,7],[6,7,8]])
a4

array([[3, 4, 5],
       [7, 8, 9],
       [2, 3, 7],
       [6, 7, 8]])

In [15]:
a4[0::3,0::2]

array([[3, 5],
       [6, 8]])

In [18]:
a4[1:3,0:2]

array([[7, 8],
       [2, 3]])