In [1]:
import pandas as pd

In [3]:
data = [10,20,30,40]
series =pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [5]:
data = [1,2,3,4]
i=['A','B','C','D']
series=pd.Series(data,index=i)
print(series)


A    1
B    2
C    3
D    4
dtype: int64


In [6]:
data = {'a': 10,'b': 20,'c': 30}
series=pd.Series(data)
print(series)

a    10
b    20
c    30
dtype: int64


In [7]:
series.replace(20,40)

a    10
b    40
c    30
dtype: int64

In [8]:
import numpy as np


In [16]:
data = np.array([100,200,300])
data={'Name':['Alice','Bob','Mary'],'Age':[25,30,34],\
      'Country':["USA","UK","AUS"]}
df = pd.DataFrame(data)
print(df)

    Name  Age Country
0  Alice   25     USA
1    Bob   30      UK
2   Mary   34     AUS


In [17]:
array = np.array([[1,2,3],[5,4,6],[7,8,9]])
print(array)
df = pd.DataFrame(array,columns=['A','B','C'])
print(df)

[[1 2 3]
 [5 4 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  5  4  6
2  7  8  9


1.Read a long text in to string that contains some punctuation marks alos
2.covert to lower case
3.Remove punctation marks
4.Split in to words using split() function 
5.Make a dictinory with each unique word as the key and its being the number of ocurrances
6.Covert the dict to dataframe and print it